offer_id: ccw713
reference:
  video: /data/ref/ccw713/winner.mp4
  script: /data/ref/ccw713/winner.txt
actors:
  - act_emu01
  - act_fox02
  - act_lion03
variants:
  identical_script: true
  minor_script_variants: 3
rubric:
  ensemble: 3
  temperature: 0.1
providers:
  tts: eleven
  face_sync: wav2lip
cost_cap: 30.0